# Generated by Django 3.0.5 on 2020-04-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=25)),
                ('nationality', models.CharField(default='INDIA', max_length=30)),
                ('profile_pic', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('started_on', models.DateTimeField()),
                ('no_of_teams', models.IntegerField(default=10)),
                ('no_of_matches', models.IntegerField(default=45)),
                ('man_of_series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Players')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teams'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('man_of_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Players')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teams')),
            ],
        ),
    ]
